import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sienna Rose Structured Flap',
    category: 'crossbody',
    category_label: 'Crossbody & Satchel',
    price: 1899,
    mrp: 2999,
    discount: '37% OFF',
    color: '#A45A49',
    color_name: 'Terracotta Sienna',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    tags: ['bestseller'],
    tag_text: 'Bestseller',
    description: 'A beautiful crossbody bag with structured flap design. Features gold-tone hardware, adjustable strap, and multiple compartments for your essentials.',
    leather_type: 'Genuine Leather',
    hardware: 'Gold-tone Metal',
    strap: 'Adjustable Crossbody Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'p2',
    name: 'Terracotta Blush Trapeze Tote',
    category: 'tote',
    category_label: 'Structured Tote',
    price: 2199,
    mrp: 3499,
    discount: '37% OFF',
    color: '#D88C7D',
    color_name: 'Blush Terracotta',
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop',
    tags: ['new'],
    tag_text: 'New Arrival',
    description: 'Spacious everyday tote with a modern silhouette. Fits your laptop, wallet, and daily essentials with ease. Dual handles and a shoulder strap for versatility.',
    leather_type: 'Genuine Leather',
    hardware: 'Antique Brass',
    strap: 'Dual Handles + Shoulder Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-16T10:00:00Z',
  },
  {
    id: 'p3',
    name: 'Desert Clay Woven Baguette',
    category: 'shoulder',
    category_label: 'Shoulder Baguette',
    price: 1699,
    mrp: 2499,
    discount: '32% OFF',
    color: '#C5A059',
    color_name: 'Ochre Clay',
    image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800&auto=format&fit=crop',
    tags: ['limited'],
    tag_text: 'Limited Run',
    description: 'A stylish shoulder bag with woven texture detail. Compact yet roomy enough for your phone, wallet, and keys. Perfect for brunch or shopping.',
    leather_type: 'Genuine Leather',
    hardware: 'Brushed Gold',
    strap: 'Fixed Shoulder Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-17T10:00:00Z',
  },
  {
    id: 'p4',
    name: 'Dusty Mauve Crescent Hobo',
    category: 'shoulder',
    category_label: 'Shoulder Hobo',
    price: 1799,
    mrp: 2799,
    discount: '36% OFF',
    color: '#B4837E',
    color_name: 'Dusty Mauve',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop',
    tags: [],
    tag_text: '',
    description: 'A relaxed hobo silhouette in soft leather. The crescent shape is both trendy and timeless. Comfortable to carry all day.',
    leather_type: 'Genuine Leather',
    hardware: 'Matte Gold Rings',
    strap: 'Adjustable Knotted Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-18T10:00:00Z',
  },
  {
    id: 'p5',
    name: 'Almond Shell Evening Clutch',
    category: 'clutch',
    category_label: 'Evening Clutch',
    price: 1299,
    mrp: 1999,
    discount: '35% OFF',
    color: '#E2CFBC',
    color_name: 'Almond Cream',
    image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?q=80&w=800&auto=format&fit=crop',
    tags: ['limited'],
    tag_text: 'Limited Run',
    description: 'An elegant evening clutch for weddings and parties. Features a jeweled clasp and detachable chain strap. Fits your phone, lipstick, and cards.',
    leather_type: 'Genuine Leather',
    hardware: 'Jeweled Clasp + Chain',
    strap: 'Detachable Chain Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-19T10:00:00Z',
  },
  {
    id: 'p6',
    name: 'Earthy Umber Drawstring Bucket',
    category: 'crossbody',
    category_label: 'Bucket Bag',
    price: 1999,
    mrp: 3299,
    discount: '39% OFF',
    color: '#4A3525',
    color_name: 'Deep Umber Earth',
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop',
    tags: ['bestseller'],
    tag_text: 'Bestseller',
    description: 'A trendy bucket bag with drawstring closure. Surprisingly spacious with interior pockets. The crossbody strap keeps your hands free.',
    leather_type: 'Genuine Leather',
    hardware: 'Burnished Brass',
    strap: 'Adjustable Crossbody Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'p7',
    name: 'Rosewood Petite Envelope Bag',
    category: 'crossbody',
    category_label: 'Crossbody Clutch',
    price: 1499,
    mrp: 2299,
    discount: '35% OFF',
    color: '#8B4A44',
    color_name: 'Rosewood Rouge',
    image: 'https://images.unsplash.com/photo-1566150902887-9679ec15d488?q=80&w=800&auto=format&fit=crop',
    tags: ['new'],
    tag_text: 'New Arrival',
    description: 'A compact envelope-style crossbody. Perfect for when you want to travel light. Fits phone, cards, and a lipstick with a sleek silhouette.',
    leather_type: 'Genuine Leather',
    hardware: 'Minimalist Brass Bar',
    strap: 'Slender Adjustable Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-21T10:00:00Z',
  },
  {
    id: 'p8',
    name: 'Sandstone Dual-Zip City Tote',
    category: 'tote',
    category_label: 'Structured Tote',
    price: 2499,
    mrp: 3999,
    discount: '38% OFF',
    color: '#D9CBB9',
    color_name: 'Sandstone Nude',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    tags: [],
    tag_text: '',
    description: 'A professional tote with 3 zippered compartments. Fits a 14" laptop with padded sleeve. Water-resistant lining keeps your things safe.',
    leather_type: 'Genuine Leather',
    hardware: 'Reinforced Gold Zippers',
    strap: 'Dual Rolled Handles',
    stock: 25,
    active: true,
    created_at: '2026-08-22T10:00:00Z',
  },
  {
    id: 'p9',
    name: 'Ivory Pearl Micro Baguette',
    category: 'clutch',
    category_label: 'Evening Clutch',
    price: 999,
    mrp: 1699,
    discount: '41% OFF',
    color: '#EFE3D0',
    color_name: 'Pearl Ivory',
    image: 'https://images.unsplash.com/photo-1614179689702-355944cd0918?q=80&w=800&auto=format&fit=crop',
    tags: ['new'],
    tag_text: 'New Arrival',
    description: 'A dainty pearl-finish baguette for cocktail hours and weddings. Fits phone, lipstick, and keys. The detachable chain makes it versatile.',
    leather_type: 'Genuine Leather',
    hardware: 'Rose Gold Chain',
    strap: 'Detachable Delicate Chain',
    stock: 25,
    active: true,
    created_at: '2026-08-23T10:00:00Z',
  },
  {
    id: 'p10',
    name: 'Cognac Vintage Doctor Satchel',
    category: 'tote',
    category_label: 'Doctor Satchel',
    price: 2799,
    mrp: 4499,
    discount: '38% OFF',
    color: '#8C5A2E',
    color_name: 'Aged Cognac',
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=800&auto=format&fit=crop',
    tags: ['bestseller'],
    tag_text: 'Bestseller',
    description: "A vintage-inspired doctor's satchel with brass twist-lock. Spacious interior with laptop sleeve and organizer pockets. A timeless everyday bag.",
    leather_type: 'Genuine Leather',
    hardware: 'Antique Brass Twist-Lock',
    strap: 'Rolled Handle + Long Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-24T10:00:00Z',
  },
  {
    id: 'p11',
    name: 'Blush Peony Half-Moon Sling',
    category: 'crossbody',
    category_label: 'Half-Moon Sling',
    price: 1399,
    mrp: 2199,
    discount: '36% OFF',
    color: '#E8B7B0',
    color_name: 'Peony Blush',
    image: 'https://images.unsplash.com/photo-1601369850088-9c4b3f7cae74?q=80&w=800&auto=format&fit=crop',
    tags: [],
    tag_text: '',
    description: 'A compact half-moon sling in soft blush leather. Ideal for hands-free day-to-brunch styling. Fits all your daily essentials.',
    leather_type: 'Genuine Leather',
    hardware: 'Rose Gold Rings',
    strap: 'Adjustable Woven Strap',
    stock: 25,
    active: true,
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'p12',
    name: 'Espresso Slouch Shoulder Bag',
    category: 'shoulder',
    category_label: 'Slouchy Shoulder',
    price: 1899,
    mrp: 2999,
    discount: '37% OFF',
    color: '#3E2A1F',
    color_name: 'Deep Espresso',
    image: 'https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=800&auto=format&fit=crop',
    tags: [],
    tag_text: '',
    description: 'A generous slouchy silhouette in rich espresso leather. Develops a beautiful patina over time. Chic day carry with a comfortable shoulder drop.',
    leather_type: 'Genuine Leather',
    hardware: 'Matte Bronze Accents',
    strap: 'Comfortable Shoulder Drop',
    stock: 25,
    active: true,
    created_at: '2026-08-26T10:00:00Z',
  },
];

export const CATEGORIES = [
  { key: 'all', label: 'All' },
  { key: 'crossbody', label: 'Crossbody' },
  { key: 'tote', label: 'Totes' },
  { key: 'shoulder', label: 'Shoulder' },
  { key: 'clutch', label: 'Clutches' },
];

// Use Unsplash images for category cards (no Supabase dependency for static export)
export const INSTA_GRID_IMAGES = MOCK_PRODUCTS.map((p, i) => ({
  src: p.image,
  alt: p.category_label,
}));

export const CATEGORY_CARDS = [
  {
    key: 'tote',
    label: 'Totes',
    subtitle: 'Everyday carry',
    img: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop',
  },
  {
    key: 'crossbody',
    label: 'Crossbody',
    subtitle: 'Hands-free',
    img: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
  },
  {
    key: 'shoulder',
    label: 'Shoulder',
    subtitle: 'Elegant drape',
    img: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop',
  },
  {
    key: 'clutch',
    label: 'Evening Clutches',
    subtitle: 'Cocktail hour',
    img: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?q=80&w=800&auto=format&fit=crop',
  },
];
